CFLAGS_MODULE += -DDEBUG
CFLAGS_MODULE += -DKERNEL_4_4_7
CFLAGS_MODULE += -DLINUX_KERNEL
obj-m += as.o
as-objs := access.o authenticated.o advertising.o blacklist.o whitelist.o debug.o hashtab.o http.o memcache.o config.o portal.o dpi-hook.o
